export default {
  components: {
    schemas: {
      RequestToken: {
        $id: '#RequestToken',
        type: 'object',
        properties: {
          token: { type: 'string' },
        },
        additionalProperties: false,
      },
      ApiKeyHeader: {
        $id: '#ApiKeyHeader',
        type: 'object',
        properties: {
          authorization: { type: 'string' },
        },
        required: ['authorization'],
      },
      RouteIdParam: {
        $id: '#RouteIdParam',
        required: ['id'],
        type: 'object',
        properties: {
          id: { type: 'string' },
        },
      },
      OrderDirectionQuery: {
        $id: '#OrderDirectionQuery',
        type: 'string',
        default: 'DESC',
        enum: ['ASC', 'DESC'],
      },
      OrderByQuery: {
        $id: '#OrderByQuery',
        type: 'string',
        default: 'created_at',
      },
      SearchQuery: {
        $id: '#SearchQuery',
        type: 'string',
        default: '',
      },
      PageQuery: {
        $id: '#PageQuery',
        type: 'string',
        default: '1',
      },
      LimitQuery: {
        $id: '#LimitQuery',
        limit: { type: 'string', default: '10' },
      },
      StatusQuery: {
        $id: '#StatusQuery',
        type: 'string',
        default: '0',
      },
      DateQuery: {
        $id: '#DateQuery',
        type: 'string',
      },
      YearQuery: {
        $id: '#YearQuery',
        type: 'string',
      },
      GetToken: {
        $id: '#GetToken',
        type: 'object',
        properties: { token: { type: 'string' } },
      },
      GetProductPhoto: {
        $id: '#GetProductPhoto',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_u_product: { type: 'integer' },
          id_m_medias: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          url: { type: 'string' },
          label: { type: 'string' },
        },
      },
      GetProfile: {
        $id: '#GetProfile',
        type: 'object',
        properties: {
          full_name: { type: 'string' },
          username: { type: 'string' },
          address: { type: 'string' },
          phone_number: { type: 'string' },
          face: { type: ['string', 'null'] },
        },
      },
      GetAccountWallet: {
        $id: '#GetAccountWallet',
        type: 'object',
        properties: {
          balance: { type: 'integer' },
          is_visible: { type: 'number' },
          wallet_name: { type: ['string', 'null'] },
          wallet_description: { type: ['string', 'null'] },
          uri: { type: ['string', 'null'] },
          label: { type: ['string', 'null'] },
        },
      },
      GetProduct: {
        $id: '#GetProduct',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_m_users: { type: 'integer' },
          product_name: { type: 'string' },
          description: { type: 'string' },
          id_cover: { type: 'integer' },
          is_visible: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          price_default: { type: 'integer' },
          price_selling: { type: 'integer' },
          qty: { type: 'integer' },
          discount: { type: 'integer' },
          cover_uri: { type: 'string' },
          cover_label: { type: 'string' },
          id_merchant: { type: 'integer' },
          no_identity: { type: 'string' },
          id_identity_photo: { type: 'integer' },
          id_market_photo: { type: 'integer' },
          market_name: { type: 'string' },
          market_address: { type: 'string' },
          market_lat: { type: 'number' },
          market_lon: { type: 'number' },
          market_close_time: { type: 'string' },
          market_visible: { type: 'integer' },
          identity_uri: { type: 'string' },
          identity_label: { type: 'string' },
          market_uri: { type: 'string' },
          market_label: { type: 'string' },
        },
      },
      GetProductCategory: {
        $id: '#GetProductCategory',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_u_product: { type: 'integer' },
          id_m_categories: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
          category: { type: 'string' },
          slug: { type: 'string' },
          description: { type: 'string' },
          is_visible: { type: 'integer' },
          id_icon: { type: 'integer' },
          url: { type: 'string' },
          label: { type: 'string' },
        },
      },
      GetOrder: {
        $id: '#GetOrder',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_m_users: { type: 'integer' },
          id_merchant: { type: 'integer' },
          transaction_token: { type: 'string' },
          total_price: { type: 'integer' },
          status: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          full_name: { type: 'string' },
          phone_number: { type: 'string' },
          address: { type: 'string' },
          id_photo: { type: 'integer' },
          uri: { type: 'string' },
          label: { type: 'string' },
          id_user_merchant: { type: 'integer' },
          id_market_photo: { type: 'integer' },
          market_name: { type: 'string' },
          market_address: { type: 'string' },
          market_lat: { type: 'integer' },
          market_lon: { type: 'integer' },
          market_close_time: { type: 'string' },
          market_visivle: { type: 'integer' },
          merchant_uri: { type: 'string' },
          merchant_label: { type: 'string' },
          cover_uri: { type: 'string' },
        },
      },
      GetMerchant: {
        $id: '#GetMerchant',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_m_users: { type: 'integer' },
          id_u_user: { type: 'integer' },
          id_identity_photo: { type: 'integer' },
          id_market_photo: { type: 'integer' },
          no_identity: { type: 'string' },
          market_name: { type: 'string' },
          market_address: { type: 'string' },
          market_uri: { type: 'string' },
          market_label: { type: 'string' },
          phone_number: { type: 'string' },
          full_name: { type: 'string' },
          market_lat: { type: 'number' },
          market_lon: { type: 'number' },
          is_visible: { type: 'integer' },
          market_close_time: { type: 'string' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      GetProductOrder: {
        $id: '#GetProductOrder',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_u_user_transaction: { type: 'integer' },
          id_m_products: { type: 'integer' },
          qty: { type: 'integer' },
          transaction_token: { type: 'string' },
          sub_total_price: { type: 'integer' },
          status: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          product_name: { type: 'string' },
          description: { type: 'string' },
          id_cover: { type: 'integer' },
          product_visible: { type: 'integer' },
          cover_uri: { type: 'string' },
          cover_label: { type: 'string' },
        },
      },
      GetCart: {
        $id: '#GetCart',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_m_users: { type: 'integer' },
          id_merchant: { type: 'integer' },
          id_m_products: { type: 'integer' },
          id_cover: { type: 'integer' },
          qty: { type: 'integer' },
          status: { type: 'integer' },
          product_name: { type: 'string' },
          description: { type: 'string' },
          uri: { type: 'string' },
          label: { type: 'string' },
          price_default: { type: 'integer' },
          price_selling: { type: 'integer' },
          discount: { type: 'integer' },
          max_qty: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      GetWallet: {
        $id: '#GetWallet',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_logo: { type: 'integer' },
          wallet_name: { type: 'string' },
          wallet_description: { type: 'string' },
          is_visible: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          craetedAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      GetMedia: {
        $id: '#GetMedia',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          uri: { type: 'string' },
          label: { type: 'string' },
          is_visible: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      GetBank: {
        $id: '#GetBank',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_logo: { type: 'integer' },
          bank_name: { type: 'string' },
          is_visible: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      GetBankUser: {
        $id: '#GetBankUser',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_m_banks: { type: 'integer' },
          id_m_users: { type: 'integer' },
          account_number: { type: 'string' },
          account_name: { type: 'string' },
          is_visible: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      GetBankUtility: {
        $id: '#GetBankUtility',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_m_banks: { type: 'integer' },
          step: { type: 'string' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      GetCategory: {
        $id: '#GetCategory',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_icon: { type: 'integer' },
          category: { type: 'string' },
          slug: { type: 'string' },
          description: { type: 'string' },
          uri: { type: 'string' },
          label: { type: 'string' },
          is_visible: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      GetUserWallet: {
        $id: '#GetUserWallet',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_u_user: { type: 'integer' },
          id_m_wallets: { type: 'integer' },
          balance: { type: 'integer' },
          is_visible: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      GetTopUp: {
        $id: '#GetTopUp',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_u_user_wallet: { type: 'integer' },
          id_m_banks: { type: 'integer' },
          balance_request: { type: 'integer' },
          balance_transfer: { type: 'integer' },
          status: { type: 'integer' },
          proof_id: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      GetWithdraw: {
        $id: '#GetWithdraw',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_u_user_wallet: { type: 'integer' },
          id_u_user_bank_account: { type: 'integer' },
          balance_request: { type: 'integer' },
          status: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      GetSingleProduct: {
        $id: '#GetSingleProduct',
        type: 'object',
        properties: {
          id_m_users: { type: 'integer' },
          product_id: { type: 'integer' },
          product_name: { type: 'string' },
          description: { type: 'string' },
          price_default: { type: 'integer' },
          price_selling: { type: 'integer', format: 'date-time' },
          qty: { type: 'integer' },
          dicount: { type: 'integer' },
          cover_uri: { type: 'string' },
          cover_label: { type: 'string' },
          market_name: { type: 'string' },
          market_address: { type: 'string' },
          market_lat: { type: 'integer' },
          markt_lon: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          images: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                product_image_id: { type: 'string' },
                uri: { type: 'string' },
                label: { type: 'string' },
                created_at: {
                  type: 'string',
                  format: 'date-time',
                },
                updated_at: {
                  type: 'string',
                  format: 'date-time',
                },
              },
            },
          },
          categories: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                category_id: { type: 'integer' },
                category: { type: 'string' },
                slug: { type: 'string' },
                description: { type: 'string' },
                icon_uri: { type: 'string' },
                icon_label: { type: 'string' },
                created_at: {
                  type: 'string',
                  format: 'date-time',
                },
                updated_at: {
                  type: 'string',
                  format: 'date-time',
                },
              },
            },
          },
        },
      },
      GetUserTransaction: {
        $id: '#GetUserTransaction',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          id_m_users: { type: 'integer' },
          id_merchant: { type: 'integer' },
          transaction_token: { type: 'string' },
          total_price: { type: 'integer' },
          status: { type: 'integer' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
          createdAt: { type: 'string', format: 'date-time' },
          updatedAt: { type: 'string', format: 'date-time' },
        },
      },
      GetFaq: {
        $id: '#GetFaq',
        type: 'object',
        properties: {
          id: { type: 'integer' },
          question: { type: 'string' },
          answer: { type: 'string' },
          created_at: { type: 'string', format: 'date-time' },
          updated_at: { type: 'string', format: 'date-time' },
        },
      },
      GetMerchantIncomes: {
        $id: '#GetMerchantIncomes',
        type: 'object',
        properties: {
          month: { type: 'string' },
          income: { type: 'integer' },
        },
      },
      GetProductId: {
        $id: '#GetProductId',
        type: 'object',
        properties: { product_id: { type: 'integer' } },
      },
      ApiResponse: {
        $id: '#ApiResponse',
        type: 'object',
        properties: {
          code: { type: 'number' },
          success: { type: 'boolean' },
          message: { type: 'string' },
        },
      },
    },
  },
};
